name: needbox_customer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  hexcolor:
  get:
  ionicons:
  google_fonts:
  cached_network_image:
  cupertino_icons:
  url_launcher:
  dio:
  carousel_slider:
  flutter_html: ^2.2.1
  http:
  lottie:
  image_picker:
  shared_preferences:
  json_annotation:
  collection: 
  hive:
  hive_flutter:
  path_provider:
  hive_generator:

  ## for datetime parse
  intl:
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  build_runner: 
  json_serializable: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
